FROM perl-base:latest

# Download and compile bcm2835 library
RUN wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.71.tar.gz && \
	tar zxvf bcm2835-1.71.tar.gz && \
	cd bcm2835-1.71 && ./configure && make && make install && \
	cd .. && rm -rf bcm2835-1.71*

RUN cpanm Device::BCM2835

COPY perl/button_server.pl /usr/local/bin/button_server.pl
RUN chmod +x /usr/local/bin/button_server.pl

CMD ["/usr/local/bin/button_server.pl"]
