FROM perl-base:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
	libdevice-serialport-perl \
	&& rm -rf /var/lib/apt/lists/*

COPY perl/rfid_server.pl /usr/local/bin/rfid_server.pl
RUN chmod +x /usr/local/bin/rfid_server.pl

CMD ["/usr/local/bin/rfid_server.pl"]
