FROM perl-base:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
	apache2 \
	apache2-bin \
	apache2-utils \
	libapache2-mod-perl2 \
	libapache2-mod-perl2-dev \
	libapache2-reload-perl \
	libembperl-perl \
	libfile-slurp-perl \
	liblwp-protocol-https-perl \
	&& rm -rf /var/lib/apt/lists/*

RUN a2enmod mpm_prefork expires remoteip headers proxy proxy_http rewrite

WORKDIR /var/www/lock_server
COPY ./htdocs /var/www/lock_server
COPY ./000-default.conf /etc/apache2/sites-available/
COPY ./mpm_prefork.conf /etc/apache2/mods-available/mpm_prefork.conf
COPY ./perl /etc/apache2/perl

RUN ln -sf /dev/stdout /var/log/apache2/access.log \
	&& ln -sf /dev/stderr /var/log/apache2/error.log

ENV PERL5LIB=/etc/apache2/perl:/usr/local/share/perl5

ENTRYPOINT ["/bin/sh", "-c", ". /etc/apache2/envvars && exec apache2 -D FOREGROUND"]
