# mpm_prefork.conf - Low memory configuration for Raspberry Pi
<IfModule mpm_prefork_module>
	StartServers             1
	MinSpareServers          1
	MaxSpareServers          1
	MaxRequestWorkers        1
	MaxConnectionsPerChild   1000
</IfModule>
