# mpm_prefork.conf - Low memory configuration for Raspberry Pi
<IfModule mpm_prefork_module>
	StartServers             2
	MinSpareServers          2
	MaxSpareServers          5
	MaxRequestWorkers       12
	MaxConnectionsPerChild 1000
</IfModule>
